// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4t2mNnDr8pauUw6LTpz328OBI15xMQ0E',
    appId: '1:786662910063:web:ba7a619fb55e2b04c3c59a',
    messagingSenderId: '786662910063',
    projectId: 'tenis-upm-2a7d8',
    authDomain: 'tenis-upm-2a7d8.firebaseapp.com',
    storageBucket: 'tenis-upm-2a7d8.firebasestorage.app',
    measurementId: 'G-5ZJMH5TS6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmfXwulWSDNVwztrH-Enc2WeF0ydHI7PY',
    appId: '1:786662910063:android:0a8ccfd673f2a25dc3c59a',
    messagingSenderId: '786662910063',
    projectId: 'tenis-upm-2a7d8',
    storageBucket: 'tenis-upm-2a7d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq9htVhaN3dtgrtXAurBa8QNhqb8Ik0Rs',
    appId: '1:786662910063:ios:2056a100ff55d30ac3c59a',
    messagingSenderId: '786662910063',
    projectId: 'tenis-upm-2a7d8',
    storageBucket: 'tenis-upm-2a7d8.firebasestorage.app',
    iosBundleId: 'com.example.aplicacionTenis',
  );
}
